"""Generate the ALTR parameter reference from the comment blocks in conf/base.

Every key in conf/base/parameters*.yml carries a comment block in a fixed
schema (meaning / unit / default / source / status). This script parses those
blocks and writes:

  docs/parameters.md    — GENERATED markdown table, one row per key
  docs/parameters.html  — GENERATED single-file explorer (search, filters)

Run:  uv run python scripts/gen_param_docs.py [--conf conf/base] [--out docs]
"""
from __future__ import annotations

import argparse
import html
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

FIELDS = ("meaning", "unit", "default", "source", "status")
KEY_RE = re.compile(r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_\"'][^:#]*?)\s*:\s*(?P<value>.*)$")
FIELD_RE = re.compile(r"^#\s*(?P<field>meaning|unit|default|source|status):\s*(?P<text>.*)$")


@dataclass
class Param:
    key: str
    file: str
    value: str
    line: int
    meaning: str = ""
    unit: str = ""
    default: str = ""
    source: str = ""
    status: str = ""
    tier: str = "advanced"

    def as_dict(self) -> dict:
        return {
            "key": self.key, "file": self.file, "value": self.value, "line": self.line,
            **{f: getattr(self, f) for f in FIELDS}, "tier": self.tier,
        }


@dataclass
class _Block:
    fields: dict = field(default_factory=dict)
    current: str | None = None

    def feed(self, comment: str) -> None:
        m = FIELD_RE.match(comment)
        if m:
            self.current = m.group("field")
            self.fields[self.current] = m.group("text").strip()
        elif self.current and comment.startswith("#"):
            self.fields[self.current] += " " + comment.lstrip("#").strip()

    def reset(self) -> None:
        self.fields, self.current = {}, None


def parse_file(path: Path, tier: str) -> list[Param]:
    """Attach each schema comment block to the next key at the block's indent."""
    params: list[Param] = []
    stack: list[tuple[int, str]] = []  # (indent, key) for nested paths
    block = _Block()
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            block.feed(stripped)
            continue
        if stripped.startswith("- "):
            continue  # list item, belongs to the key above
        m = KEY_RE.match(raw)
        if not m:
            continue
        indent = len(m.group("indent"))
        key = m.group("key").strip().strip("\"'")
        value = m.group("value").strip()
        while stack and stack[-1][0] >= indent:
            stack.pop()
        dotted = ".".join([k for _, k in stack] + [key])
        if "meaning" in block.fields:
            params.append(Param(key=dotted, file=path.name, value=value or "(block)", line=lineno,
                                tier=tier, **{f: block.fields.get(f, "") for f in FIELDS}))
        block.reset()
        if value == "":
            stack.append((indent, key))
    return params


def collect(conf_dir: Path) -> list[Param]:
    out: list[Param] = []
    for path in sorted(conf_dir.glob("parameters*.yml")):
        tier = "user" if path.name == "parameters.yml" else ("reporting" if "reporting" in path.name else "advanced")
        out.extend(parse_file(path, tier))
    return out


BANNER = "GENERATED by scripts/gen_param_docs.py — edit the comment blocks in conf/base/*.yml, not this file."


def render_md(params: list[Param]) -> str:
    lines = [f"<!-- {BANNER} -->", "# ALTR parameters", "",
             f"{len(params)} parameters. Tier `user` = `conf/base/parameters.yml`, the file to edit for a normal run; "
             "`advanced` = per-pipeline files; `reporting` = presentation only.", "",
             "| key | tier | value | unit / range | meaning | default | source | status | file |",
             "|---|---|---|---|---|---|---|---|---|"]
    esc = lambda s: s.replace("|", "\\|")
    for p in params:
        lines.append(f"| `{p.key}` | {p.tier} | `{esc(p.value)}` | {esc(p.unit)} | {esc(p.meaning)} | {esc(p.default)} | {esc(p.source)} | {esc(p.status)} | {p.file}:{p.line} |")
    return "\n".join(lines) + "\n"


HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ALTR Parameters</title>
<style>
:root{--bg:#fbfaf7;--fg:#1e1e1c;--muted:#6b6a64;--line:#e4e1d8;--card:#fff;--acc:#1f5f8b;--user:#2a7d4f;--adv:#8a6d1f;--rep:#6b6a64;--dead:#a33}
@media(prefers-color-scheme:dark){:root{--bg:#171716;--fg:#ebe9e2;--muted:#9c9a92;--line:#33322e;--card:#1f1f1d;--acc:#7fb3d9;--user:#6fc292;--adv:#d4b25a;--rep:#9c9a92;--dead:#e07a7a}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.45 -apple-system,Segoe UI,Helvetica,Arial,sans-serif}
header{padding:28px 32px 16px;border-bottom:1px solid var(--line)}h1{margin:0 0 4px;font-size:22px;font-weight:600}
.sub{color:var(--muted);font-size:13px}.ctl{display:flex;gap:12px;flex-wrap:wrap;padding:14px 32px;border-bottom:1px solid var(--line);align-items:center}
input[type=search]{flex:1;min-width:220px;padding:8px 10px;border:1px solid var(--line);border-radius:6px;background:var(--card);color:var(--fg);font-size:14px}
.chip{border:1px solid var(--line);border-radius:999px;padding:4px 11px;font-size:13px;cursor:pointer;background:var(--card);color:var(--fg)}
.chip.on{background:var(--acc);border-color:var(--acc);color:#fff}
main{padding:12px 32px 48px}.count{color:var(--muted);font-size:13px;margin:8px 0 12px}
.row{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:10px 14px;margin-bottom:8px;cursor:pointer}
.row .top{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}.k{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14px;font-weight:600}
.v{font-family:ui-monospace,Menlo,monospace;font-size:13px;color:var(--acc)}.tag{font-size:11px;padding:1px 7px;border-radius:4px;border:1px solid currentColor}
.t-user{color:var(--user)}.t-advanced{color:var(--adv)}.t-reporting{color:var(--rep)}.s-dead,.s-unreach{color:var(--dead)}
.m{color:var(--fg);margin-top:4px;font-size:14px}.d{display:none;margin-top:8px;font-size:13px;color:var(--muted);border-top:1px dashed var(--line);padding-top:8px}
.row.open .d{display:grid;grid-template-columns:90px 1fr;gap:3px 10px}.d b{color:var(--fg);font-weight:500}
</style></head><body>
<header><h1>ALTR parameters</h1><div class="sub">__COUNT__ parameters from <code>conf/base/parameters*.yml</code>. __BANNER__ Click a row for unit, default, source and file.</div></header>
<div class="ctl"><input id="q" type="search" placeholder="search key, meaning, source…" autofocus>
<span class="chip on" data-f="tier" data-v="">all tiers</span><span class="chip" data-f="tier" data-v="user">user</span><span class="chip" data-f="tier" data-v="advanced">advanced</span><span class="chip" data-f="tier" data-v="reporting">reporting</span>
<span class="chip" data-f="status" data-v="gated">gated</span><span class="chip" data-f="status" data-v="dead">dead / unreachable</span></div>
<main><div class="count" id="count"></div><div id="list"></div></main>
<script>
const P=__DATA__;const list=document.getElementById('list'),q=document.getElementById('q'),count=document.getElementById('count');
const f={tier:'',status:''};const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function sclass(s){return /dead|unreach/i.test(s)?'s-dead':/gated/i.test(s)?'s-gated':''}
function render(){const t=q.value.toLowerCase();let n=0;list.innerHTML=P.filter(p=>{
 if(f.tier&&p.tier!==f.tier)return false;
 if(f.status==='gated'&&!/gated/i.test(p.status))return false;
 if(f.status==='dead'&&!/dead|unreach/i.test(p.status))return false;
 return !t||[p.key,p.meaning,p.source,p.unit,p.status,p.file].join(' ').toLowerCase().includes(t)}).map(p=>{n++;return `<div class="row"><div class="top"><span class="k">${esc(p.key)}</span><span class="v">${esc(p.value)}</span><span class="tag t-${p.tier}">${p.tier}</span><span class="tag ${sclass(p.status)}">${esc(p.status.split(/\\s|—/)[0])}</span></div><div class="m">${esc(p.meaning)}</div><div class="d"><b>unit</b><span>${esc(p.unit)}</span><b>default</b><span>${esc(p.default)}</span><b>source</b><span>${esc(p.source)}</span><b>status</b><span>${esc(p.status)}</span><b>file</b><span>${esc(p.file)}:${p.line}</span></div></div>`}).join('');
 count.textContent=n+' of '+P.length+' parameters';}
list.addEventListener('click',e=>{const r=e.target.closest('.row');if(r)r.classList.toggle('open')});
q.addEventListener('input',render);
document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{const k=c.dataset.f,v=c.dataset.v;
 if(k==='tier'){f.tier=v;document.querySelectorAll('.chip[data-f=tier]').forEach(x=>x.classList.toggle('on',x.dataset.v===v))}
 else{f.status=f.status===v?'':v;document.querySelectorAll('.chip[data-f=status]').forEach(x=>x.classList.toggle('on',x.dataset.v===f.status))}
 render()}));
render();
</script></body></html>
"""


def render_html(params: list[Param]) -> str:
    data = json.dumps([p.as_dict() for p in params], ensure_ascii=False).replace("</", "<\\/")
    return (HTML_TEMPLATE.replace("__DATA__", data).replace("__COUNT__", str(len(params)))
            .replace("__BANNER__", html.escape(BANNER)))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--conf", default="conf/base", type=Path)
    ap.add_argument("--out", default="docs", type=Path)
    args = ap.parse_args()
    params = collect(args.conf)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "parameters.md").write_text(render_md(params))
    (args.out / "parameters.html").write_text(render_html(params))
    print(f"{len(params)} parameters -> {args.out / 'parameters.md'}, {args.out / 'parameters.html'}")


if __name__ == "__main__":
    main()
