name: Deploy Kedro Viz to GCP

on:
  push:
    branches:
      - main

env:
  GCP_BUCKET_NAME: trisk.1in1000.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry run pip install kedro-viz
          
      - name: Build Kedro Viz
        run: |
          poetry run kedro viz build
          ls -la build  # Debug step to verify build directory contents
          
      - name: Authenticate to Google Cloud via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/350220397525/locations/global/workloadIdentityPools/github-pool/providers/theia"
          service_account: "github-ci@cloud-1in1000.iam.gserviceaccount.com"
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
          
      - name: Deploy to GCP Storage
        run: |
          gsutil -m rsync -r build gs://${{ env.GCP_BUCKET_NAME }}/viz
          
      - name: Invalidate Cloud CDN Cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache viz-url-map --path "/*" 